### ISSUE TITLE
Windows 10 x64 Julia 1.6.3 OpenCV 4.5.2 bindings are not working correctly

### ISSUE THREAD

**Issue by vladimir12345** [JuliaImages/OpenCV.jl#12]
Windows 10 x64 Julia 1.6.3 OpenCV 4.5.2 bindings are not working correctly.
According to the OpenCV Julia bindings developer, the OpenCV Julia bindings work correctly with the latest OpenCV 4.5.4 release.
Can you update OpenCV Julia package with this OpenCV version?
Otherwise it's useless.
Is there a chance the OpenCV build will include intel IPP and tbb?
Also having OpenCV CUDA module would be super great :-)

**Comment by stemann** [comment]
Sounds like this can be closed, @ashwani-rathee ? Cf. passing tests in https://github.com/JuliaImages/OpenCV.jl/pull/25.

IPP/TBB/CUDA stuff requests can be filed in separate issues.

**Comment by ViralBShah** [comment]
Working fine in the latest CI.
