### ISSUE TITLE
Unit Test coverage

### ISSUE THREAD

**Issue by vladimir12345** [JuliaImages/OpenCV.jl#13]
Is there a unit test coverage of the OpenCV package?
This package is not yet ready for production use (or any use at all) and it should be clearly stated.

**Comment by stemann** [comment]
Yes there is - though the test coverage is quite low, cf. [test](https://github.com/JuliaImages/OpenCV.jl/tree/master/test).

The tests should be enabled for CI by #25

**Comment by stemann** [comment]
On a related note, OpenCV (proper) test coverage is also quite low, e.g. for SimpleBlobDetector:
* Python: https://github.com/opencv/opencv/blob/4.x/modules/python/test/test_misc.py#L739 , and https://github.com/opencv/opencv/blob/4.x/modules/python/test/test_features2d.py
* C++: https://github.com/opencv/opencv/blob/4.x/modules/features2d/test/test_blobdetector.cpp

You have to look at the Java wrapper to have something more proper in terms of tests: https://github.com/opencv/opencv/blob/4.x/modules/features2d/misc/java/test/SIMPLEBLOBFeatureDetectorTest.java

**Comment by rakeshksr** [comment]
@vladimir12345 as @stemann mentioned test coverage is quite low. It is anticipated that test coverage will expand as the project evolves.
You can find current coverage report at `README.md` coverage badge.
