### ISSUE TITLE
Julia 1.8.3 can't "add OpenCV"  CxxWrap issues.

### ISSUE THREAD

**Issue by MontyTHall2** [JuliaImages/OpenCV.jl#17]
I'm running Julia 1.8.3.  I can get CxxWrap 0.12 (and corresponding libcxxwrap-julia v0.9.0) to "add CxxWrap" and Pkg.precompile() fine.  In fact, I can "import CxxWrap" - no problem.  What I'm finding is that when I "add OpenCV" it's version of CxxWrap doesn't work for me.  The CxxWrap wants a version of libcxxwrap-julia to be less than 0.9.0.  The problem is that when I bump libcxxxwrap-julia down one notch to 0.8.3 - I can't build it.  I suspect CxxWrap 0.11 doesn't like Julia 1.8.3.  Not sure what to do.

**Comment by MontyTHall2** [comment]
Here's what I did.  I "rm CxxWrap" and I went into .julia/packages and delted "CxxWrap".  Then I "dev OpenCV" and hacked the Project.toml file to only use CxxWrap 0.12.  Then I added CxxWrap 0.12 "add CxxWrap".  Which automatically updated OpenCV.  I can now "using OpenCV".  I still have to test it.

**Comment by MontyTHall2** [comment]
Well, I was able to load and image and display it.  As a seasoned c++/python opencv user, I'll have to explore how to use OpenCV from Julia.

**Comment by stemann** [comment]
Sounds like this can be closed, @ashwani-rathee ? Cf. passing tests in #25.

**Comment by ashwani-rathee** [comment]
Installable and precompiles just fine on Julia 1.8, locally tested
