### ISSUE TITLE
[Request] Maintenance/Work of OpenCV.jl being done in JuliaImages

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/OpenCV.jl#19]
Hey Archit, I wanted to ask if OpenCV.jl could be maintained in JuliaImages instead of being maintained here. There have not been much developement on this project of late and usually lagging behind, lack of availability of docs and limited tests. It would be great if you could maintain this project in JuliaImages and we also could help more there.

**Comment by timholy** [comment]
I think that would be good in principle, although I note a lack of submitted PRs. Thus, no one has given @archit120 a chance to act as maintainer for external contributions, and there's currently no evidence that development would be any faster if it occurred within JuliaImages.

But if @archit120 isn't planning to maintain this, transferring it would make sense for long-term viability.

**Comment by archit120** [comment]
I unfortunately do not have enough bandwidth to work as a maintainer for
this project. Have no problems with it being transferred if it leads to
more active development.

**Comment by timholy** [comment]
Thanks, @archit120. I just sent you an invitation to JuliaImages, once you accept that you should be able to transfer it. Thanks for your important contributions to creating this package, I hope another champion takes it up again!

**Comment by ashwani-rathee** [comment]
Thanks @archit120 for your amazing contributions, looking forward to further developement of OpenCV.jl
