### ISSUE TITLE
Registration of new version

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/OpenCV.jl#21]
@JuliaRegistrator register

**Comment by ashwani-rathee** [comment]
@JuliaRegistrator register

**Comment by stemann** [comment]
I guess this can be closed?

**Comment by ashwani-rathee** [comment]
I generally like to keep it open and separate for registration

**Comment by stemann** [comment]
OK... I was just aiming for getting some issues closed as you may have noticed :-)

**Comment by ashwani-rathee** [comment]
I appreciate it, and will review the tests asap I could, it was much needed :)

**Comment by rakeshksr** [comment]
@JuliaRegistrator register
