### ISSUE TITLE
Rebuild JLL for 1.10 compatibility

### ISSUE THREAD

**Issue by maleadt** [JuliaImages/OpenCV.jl#23]
OpenCV.jl currently crashes on PkgEval, and needs a rebuild of the CxxWrap-based JLL for compatibility. See also: https://github.com/JuliaInterop/CxxWrap.jl/issues/362#issuecomment-1550875385

In the meantime, I'll remove OpenCV.jl from the PkgEval testing schedule, but feel free to ping me when this is fixed.

**Comment by stemann** [comment]
WIP: https://github.com/JuliaPackaging/Yggdrasil/pull/7152

**Comment by stemann** [comment]
There should be a re-built OpenCV JLL available very soon: https://github.com/JuliaRegistries/General/pull/89392
