### ISSUE TITLE
Documentation page offline

### ISSUE THREAD

**Issue by jcbritobr** [JuliaImages/OpenCV.jl#24]
Hello, the documentation page below is offline
https://juliaimages.org/OpenCV.jl/latest/

**Comment by ashwani-rathee** [comment]
This package is on survival mode only: https://juliaimages.org/OpenCV.jl/dev/ and more documentation is needed

**Comment by stemann** [comment]
With the link in the About column on [the GitHub page](https://github.com/JuliaImages/OpenCV.jl) referring to the `dev` documentation, I guess we can close this @ashwani-rathee ?
