### ISSUE TITLE
Feature request: `Base.show` for `OpenCV.Mat` image

### ISSUE THREAD

**Issue by rakeshksr** [JuliaImages/OpenCV.jl#30]
@ashwani-rathee 

It's good to have `Base.show` method to display images in pluto.jl directly.

Currently, I implemented a simple(hacky) method for my needs to show images in pluto.jl
```julia
using ImageIO
using ImageShow
using ImageCore
using OpenCV

function Base.show(io::IO, ::MIME"image/png", opencv_img::OpenCV.Mat{UInt8})
	# opencv_img = OpenCV.cvtColor(opencv_img, OpenCV.COLOR_BGR2RGB)
	prmt_img::Array{UInt8, 3} = permutedims(opencv_img, (1, 3, 2))
	if size(prmt_img, 1) == 1
		img2d = dropdims(prmt_img; dims=1)
		img = colorview(Gray, float.(img2d)./255)
	else
		img = colorview(RGB, float.(prmt_img)./255)
	end
		
	Base.show(io, MIME"image/png"(), img)
end
```

**Comment by ashwani-rathee** [comment]
Can you please make a PR? I would love to get it in

**Comment by rakeshksr** [comment]
IMO depending on `ImageIO.jl`, `ImageShow.jl` and ` ImageCore.jl` for Base.show makes OpenCV.jl little heavy. From what I understood correctly, [ImageShow/showmime.jl](https://github.com/JuliaImages/ImageShow.jl/blob/05ec585f91673f96fdd5d5885a1fad719affb917/src/showmime.jl) uses [FileIO.jl](https://github.com/JuliaIO/FileIO.jl) for Base.show methods.

Why don't follow similar approach by adding FileIo.jl integration with opencv.jl then write Base.show method on top of that?
This makes OpenCV.jl not depends on ImageIO, ImageShow and ImageCore.
 
Maybe we can depends on ImageCore for OpenCV.jl <=> Images.jl conversion in future.
