### ISSUE TITLE
Installation error of OpenCV.jl with julia 1.10.2.

### ISSUE THREAD

**Issue by kyhps2** [JuliaImages/OpenCV.jl#39]
There is an installation error of OpenCV.jl with julia 1.10.2.
I got error message as follows.

```julia
(new_env) pkg> add OpenCV

 Updating `D:\Study_00_Programming\Julia\SourceCodes\new_env\Manifest.toml`
⌅ [1f15a43c] + CxxWrap v0.13.4
  [692b3bcd] + JLLWrappers v1.5.0
  [1914dd2f] + MacroTools v0.5.13
...
[83775a58] + Zlib_jll v1.2.13+1
[8e850ede] + nghttp2_jll v1.52.0+1
[3f19e933] + p7zip_jll v17.4.0+2
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ✗ CxxWrap
  ✗ OpenCV_jll
  ✗ OpenCV
  0 dependencies successfully precompiled in 6 seconds. 43 already precompiled.
  3 dependencies errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

```

What's wrong with OpenCV.jl ?

**Comment by ashwani-rathee** [comment]
Hey, Images.jl is the standard package for image processing in Julia and OpenCV.jl is barely standing in older versions if even then.

**Comment by jgardona** [comment]
Guys are not maintaining julia packages. This issue is not only with this package, but many other. Don´t know whats happening with julia language. Its losing traction.

**Comment by marcoxa** [comment]
> Hey, Images.jl is the standard package for image processing in Julia and OpenCV.jl is barely standing in older versions if even then.

Hi

I am sorry, but this comment contradicts the statement that `OpenCV` is now part of `JuliaImages`.
But, even if that were not the case, we still have the problem of loading time for large `.tif` images with the vanilla `JuliaImages` library, even when using `ImageMagik`.

This seems a problem related to `CxxWrap` and its artifact.  It'd be better stating that fact somewhere (and nag the `CxxWrap` maintainers).

All the best

Marco

PS No.  I am a "luser", not a developer!

**Comment by marcoxa** [comment]
> Guys are not maintaining julia packages. This issue is not only with this package, but many other. Don´t know whats happening with julia language. Its losing traction.

Too must testosterone (and masochism) flowing towards crustaceans :)

**Comment by andrew-saydjari** [comment]
Looks like the simple fix is to bump the Cxx compat to include 0.16 (or anything higher than 0.15) rather than the 0.13 max that is currently there. Can someone with permissions do that? (see this thread https://github.com/JuliaInterop/CxxWrap.jl/issues/424)

**Comment by likanzhan** [comment]
Is there an update on this problem?

**Comment by andrew-saydjari** [comment]
I think the solution I suggested could be an easy fix, though I don't have the permissions and/or time to fix. I ended up taking @ashwani-rathee's advice, which worked for my case.

I had installed a slightly old package, tried to use an image with it, and it return error messages asking me to add OpenCV.jl (and some other packages). However, ignoring those error message requests and just installing and using Images.jl (and some of the other modern images ecosystem like ImageIO.jl) fixed all of my problems. So it seems like maybe part of the problem is that the error messages are leading people to older packages rather that the newer ecosystem? In any case, you should give that a try, unless OpenCV.jl is an explicit dependency of a package you are trying to use.

**Comment by likanzhan** [comment]
@andrew-saydjari Thanks. But OpenCV.jl is The package I'm trying to use.

**Comment by ViralBShah** [comment]
Attempting to see if we can get this package working and refreshed (even though Images.jl is the way to go). See #47. Help and maintainers appreciated.

**Comment by marcoxa** [comment]
Hi

The issue is the following.

The binding is generated from files that are created by a - ahem - less
than documented Python script ('hdr_parser.py') in a - ahem - even less
documented format, due to the macrology used in the OpenCV source code.
The setup is the same as the one used by the Python binding.  Note that the
Java binding seems to be built in a different way, but I have not really
looked at it.

The result file is munged to produce the Julia binding; see the .
../opencv_contrib/modules/julia/gen.  That’s where the work must be done.
And that requires knowledge of the Julia low-level binding machinery and of
the file generated by the Python header parser.

Unless some better, Python-less, solution can be found.

Marco Antoniotti
Somewhere over the Rainbow

**Comment by ksil** [comment]
Thanks for the help @ViralBShah. Facing the same issues and came across this timely thread! As another data point, I compiled `libcxxwrap-julia` (0.13.2) from source and successfully overrode the artifact (confirmed with ` CxxWrap.prefix_path()`, `julia` 1.11.0, `CxxWrap` 0.16.0). I then built OpenCV from source (4.10.0) along with the julia module and ended up with this compiler error:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/pop_heap.h:53:7: error: no matching function for call to '__sift_up'
      std::__sift_up<_AlgPolicy>(__first, __hole, __comp_ref, __hole - __first);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/pop_heap.h:65:8: note: in instantiation of function template specialization 'std::__pop_heap<std::_ClassicAlgPolicy, std::less<cv::Point_<float>>, std::__wrap_iter<cv::Point_<float> *>>' requested here
  std::__pop_heap<_ClassicAlgPolicy>(std::move(__first), std::move(__last), __comp, __len);
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/queue:1095:12: note: in instantiation of function template specialization 'std::pop_heap<std::__wrap_iter<cv::Point_<float> *>, std::less<cv::Point_<float>>>' requested here
    _VSTD::pop_heap(c.begin(), c.end(), comp);
           ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/stl.hpp:271:52: note: in instantiation of member function 'std::priority_queue<cv::Point_<float>>::pop' requested here
    wrapped.method("pq_pop!", [] (WrappedT& v) { v.pop(); });
                                                   ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/module.hpp:1225:5: note: in instantiation of function template specialization 'jlcxx::stl::WrapPriorityQueue::operator()<jlcxx::TypeWrapper<std::priority_queue<cv::Point_<float>>>>' requested here
    apply_ftor(TypeWrapper<AppliedT>(m_module, app_dt, app_box_dt));
    ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/module.hpp:1174:34: note: in instantiation of function template specialization 'jlcxx::TypeWrapper<jlcxx::Parametric<jlcxx::TypeVar<1>>>::apply_internal<std::priority_queue<cv::Point_<float>>, jlcxx::stl::WrapPriorityQueue>' requested here
    auto dummy = {this->template apply_internal<AppliedTypesT>(std::forward<FunctorT>(apply_ftor))...};
                                 ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/stl.hpp:387:63: note: (skipping 8 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    TypeWrapper1(mod, StlWrappers::instance().priority_queue).apply<std::priority_queue<T>>(WrapPriorityQueue());
                                                              ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/module.hpp:241:6: note: in instantiation of function template specialization 'jlcxx::create_if_not_exists<std::vector<cv::Point_<float>> &>' requested here
    (create_if_not_exists<Args>(), ...);
     ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/module.hpp:779:29: note: in instantiation of member function 'jlcxx::FunctionWrapper<void, cv::Subdiv2D &, std::vector<cv::Point_<float>> &>::FunctionWrapper' requested here
    auto* new_wrapper = new FunctionWrapper<R, Args...>(this, f);
                            ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/module.hpp:773:12: note: in instantiation of function template specialization 'jlcxx::Module::method_helper<void, cv::Subdiv2D &, std::vector<cv::Point_<float>> &>' requested here
    return method_helper(name, std::function<R(ArgsT...)>(std::forward<LambdaT>(lambda)), std::move(extraData));
           ^
/Users/kevin/repos/libcxxwrap-julia/include/jlcxx/module.hpp:614:12: note: in instantiation of function template specialization 'jlcxx::Module::lambda_helper<void, (lambda at /Users/kevin/repos/opencv/build/modules/julia/gen/autogen_cpp/cv_core.cpp:433:63), cv::Subdiv2D &, std::vector<cv::Point_<float>> &>' requested here
    return lambda_helper(name, std::forward<LambdaT>(lambda), &LambdaT::operator(), std::move(extraData));
           ^
/Users/kevin/repos/opencv/build/modules/julia/gen/autogen_cpp/cv_core.cpp:433:9: note: in instantiation of function template specialization 'jlcxx::Module::method<(lambda at /Users/kevin/repos/opencv/build/modules/julia/gen/autogen_cpp/cv_core.cpp:433:63), true>' requested here
    mod.method("jlopencv_cv_cv_Subdiv2D_cv_Subdiv2D_insert",  [](cv::Subdiv2D& cobj, vector<Point2f>& ptvec) { cobj.insert(ptvec);  ;});
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/push_heap.h:32:6: note: candidate template ignored: substitution failure [with _AlgPolicy = std::_ClassicAlgPolicy, _Compare = std::less<cv::Point_<float>> &, _RandomAccessIterator = std::__wrap_iter<cv::Point_<float> *>]
void __sift_up(_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare&& __comp,
```

I'm on an intel macbook pro running Sonoma 14.2.1.

So there's some weirdness happening with the OpenCV module in addition to the artifacts potentially... Let me know if I can help guinea pig anything. I may try building with older versions of everything involved.

**Comment by ViralBShah** [comment]
Where is this compiler error? I assume this is in the building of the C++ bindings. I think the first step might be to try with Julia 1.10, since 1.11 does need some updates based on the comments in the Yggdrasil PR.

cc @barche

**Comment by ViralBShah** [comment]
It would also be nice to start getting a PR going on Yggdrasil for others to try this out.

**Comment by ksil** [comment]
Yeah, sorry, this is indeed in the building of the C++ bindings in the OpenCV repo. Will try that out...

**Comment by barche** [comment]
The particular error above may actually be related to added STL support in libcxxwrap, which seems problematic on some apple compilers. I think it's best to try to build using binarybuilder, maybe in a draft PR on Yggdrasil.

**Comment by barche** [comment]
I updated PR https://github.com/JuliaPackaging/Yggdrasil/pull/8820 and created an opencv_contrib branch with the changes here: https://github.com/barche/opencv_contrib/tree/julia-fixes

**Comment by ViralBShah** [comment]
@ksil Could you try out the binaries from the Yggdrasil PR?

**Comment by barche** [comment]
I tried them and they don't work with the error that C++ type `float` is not mapped to Julia (❓). The reason isn't immediately obvious, so I'll need to do some debugging on this.

**Comment by ViralBShah** [comment]
Very close to running again: https://github.com/JuliaImages/OpenCV.jl/pull/47

**Comment by ViralBShah** [comment]
Would be nice if you can try the dev version and verify.
