### ISSUE TITLE
How to read FileStorage?

### ISSUE THREAD

**Issue by liupgd** [JuliaImages/OpenCV.jl#7]
Hi, I can write FileStorage(yaml file), but I dont find how to read FileStoarge data. Any tips? Thanks.

**Comment by rakeshksr** [comment]
@liupgd May be these will help
https://docs.opencv.org/4.x/dd/d74/tutorial_file_input_output_with_xml_yml.html 
https://docs.opencv.org/4.x/da/d56/classcv_1_1FileStorage.html

If your issue not solved, feel free to reopen this issue.
